
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
development:
  <<: *default
  database: glitter_development
test:
  <<: *default
  database: glitter_test
production:
  <<: *default
  database: glitter_production
